services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

  # PGAdmin Service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
    networks:
      - app-network

  # PHP mit Apache Service (Website-Service)
  php-apache:
    image: php:8.1-apache
    container_name: php-apache-container
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html  
    ports:
      - "9090:80"  # Zugriff auf PHP-Webseite unter Port 9090
    networks:
      - app-network
    depends_on:
      - postgres
    command: bash -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql && apache2-foreground"

volumes:
  postgres-data: {}

networks:
  app-network:
    driver: bridge
